from app.models import db, Comments

def seed_comments():
    comment1
    comment2
    comment3
    comment4
    comment5
    comment6
    comment7
    comment8
    comment9
    comment10
    comment11
    comment12
    comment13
    comment14
    comment15
    comment16
    comment17
    comment18
    comment19
    comment20
    comment21
    comment22
    comment23
    comment24
    comment25
    comment26
    comment27
    comment28
    comment29
    comment30

    db.session.add(comment1)
    db.session.add(comment2)
    db.session.add(comment3)
    db.session.add(comment4)
    db.session.add(comment5)
    db.session.add(comment6)
    db.session.add(comment7)
    db.session.add(comment8)
    db.session.add(comment9)
    db.session.add(comment10)
    db.session.add(comment11)
    db.session.add(comment12)
    db.session.add(comment13)
    db.session.add(comment14)
    db.session.add(comment15)
    db.session.add(comment16)
    db.session.add(comment17)
    db.session.add(comment18)
    db.session.add(comment19)
    db.session.add(comment20)
    db.session.add(comment21)
    db.session.add(comment22)
    db.session.add(comment23)
    db.session.add(comment24)
    db.session.add(comment25)
    db.session.add(comment26)
    db.session.add(comment27)
    db.session.add(comment28)
    db.session.add(comment29)
    db.session.add(comment30)
